// Editorial session copy for Points.
// Loaded after the main single-file app so the point data stays easy to revise separately.
(() => {
  if (typeof POINTS === 'undefined' || !Array.isArray(POINTS)) return;

  const SESSION_COPY = {
  "shenmen": {
    "why": "In ear-acupuncture traditions, Shén Mén — Spirit Gate — is often used as a settling point when attention feels crowded or overstimulated.",
    "script": "Find a position where your body can release some of its weight — chair, floor, wherever feels easy.\n\nLet your eyes close, or soften your gaze. Notice the places where your body is already being supported.\n\nBring your attention to Shén Mén: Spirit Gate. In ear-acupuncture traditions, it is a point associated with settling and making a little room around an overfull mind.\n\nPicture a small gate there. Nothing dramatic. Just a hinge loosening.\n\nBreathe in, and notice one thought that has been circling — an email, a conversation, something unfinished.\n\nBreathe out, and imagine setting that thought just outside the gate. Not solved. Not erased. Simply somewhere you do not have to hold it for this breath.\n\nAgain. In — notice what else is asking for your attention.\nOut — give it a little distance.\n\nYou do not need an empty mind. A little more space is enough.\n\nStay with the image for a few breaths: gate open, thoughts allowed to come and go, your body still here beneath all of it.\n\nWhen you are ready, notice the weight of your body again, the sounds around you, and let your eyes open."
  },
  "anmian": {
    "why": "Ānmián translates to Peaceful Sleep and is traditionally associated with the transition from wakefulness into rest.",
    "script": "Settle into bed, or wherever you plan to rest. Let your shoulders fall away from your ears.\n\nBring your attention to the soft area just behind and below the ear, near the base of the skull. This is Ānmián — Peaceful Sleep.\n\nNo pressure is needed. Let the point simply give your attention somewhere quiet to land.\n\nBreathe in slowly. As you breathe out, imagine warmth gathering there.\n\nLet that warmth travel down the neck and across the shoulders, not making anything happen, just giving the day somewhere to loosen.\n\nNotice the weight of the blanket. The mattress beneath you. The fact that, for this moment, you do not need to hold yourself up.\n\nIf a thought arrives, let it stay distant — like a television in another room. You can hear it without going to investigate.\n\nWarmth at the base of the skull. Shoulders heavy. Breath unhurried.\n\nThere is nowhere else you need to be for this breath.\n\nLet your attention grow softer around the edges, and drift whenever sleep arrives."
  },
  "yintang": {
    "why": "Located between the eyebrows, Yìn Táng is traditionally associated with quieting mental activity and bringing attention back to one place.",
    "script": "Bring your attention to the space between your eyebrows. You do not need to touch it — just notice the area.\n\nThis is Yìn Táng: Hall of Impression.\n\nTake a breath in and notice whether your brow is working harder than it needs to — furrowed, lifted, held.\n\nBreathe out and let that small area soften. Let the skin across your forehead feel a little wider.\n\nIf a worry appears, you do not need to answer it. Notice the thought, then notice the brow.\n\nIn — thought present.\nOut — forehead soft.\n\nAgain. Let the thought do whatever it does while the muscles around it unclench.\n\nThe problem does not need to disappear for your face to stop bracing against it.\n\nStay here for a few breaths, returning to this one small space whenever your attention wanders.\n\nWhen you are ready, let your awareness widen back out to the room."
  },
  "hegu": {
    "why": "Hé Gǔ — Union Valley — is a well-known hand point traditionally associated with held tension and physical discomfort.",
    "script": "Find the soft web between your thumb and index finger on either hand. You can rest your attention there, or touch it lightly if that feels comfortable.\n\nThis is Hé Gǔ: Union Valley.\n\nNotice the hand first. Is it gripping, curling, or holding more effort than the moment requires?\n\nBreathe out and let the fingers loosen.\n\nNow notice the jaw.\nOut — let the teeth part slightly.\n\nNotice the shoulders.\nOut — let them drop away from the ears.\n\nCome back to the hand. Let the palm rest open, with nothing to grip.\n\nYou are not asking the body to become perfectly loose. You are noticing where effort can be reduced by one degree.\n\nOne more breath: notice what is still held.\n\nAs you exhale, let whatever can soften, soften.\n\nRest there for a few breaths before returning to what comes next."
  },
  "neiguan": {
    "why": "Nèi Guān — Inner Gate — is a wrist point traditionally used as a steady place of attention when the body feels unsettled or rushed.",
    "script": "Turn one wrist so your palm faces up. About three finger-widths below the wrist crease, between the two tendons, is Nèi Guān — Inner Gate.\n\nRest the fingers of your other hand there lightly, or simply notice the place.\n\nWhen everything feels fast, give your attention one thing that is not moving: the contact of your fingers at the wrist.\n\nBreathe in without trying to take in more air than feels natural.\n\nBreathe out slowly, and feel the hand beneath your fingers.\n\nAgain. In — notice the rush.\nOut — return to the wrist.\n\nThe goal is not to force your heartbeat, thoughts, or sensations into a different state. Just give them a steadier rhythm to sit beside.\n\nNotice the support beneath your feet or your body. Notice the temperature of the air. Notice the Inner Gate under your fingers.\n\nIf your attention races ahead, bring it back to one physical fact: I am here, and my hand is here.\n\nStay with that simple anchor for a few more breaths.\n\nWhen you are ready, loosen your hand and let your attention widen again."
  },
  "baihui": {
    "why": "At the crown of the head, Bǎi Huì — Hundred Meetings — is traditionally described as a place where many pathways meet, making it a fitting focus for a scattered mind.",
    "script": "Bring your attention to the crown of your head — the highest point, roughly where a line rising from each ear would meet.\n\nThis is Bǎi Huì: Hundred Meetings.\n\nImagine a fine thread lifting gently from that point. Not pulling — just giving the spine a little more length.\n\nBreathe out and let the shoulders soften beneath it.\n\nYour attention may be in several places at once: the next task, an unanswered message, something from earlier.\n\nChoose one of those threads.\n\nBreathe in — notice where your mind went.\nBreathe out — gather it back to the crown.\n\nAgain. Another thread, another return.\n\nYou are not forcing concentration. You are practicing return.\n\nScattered light becomes clearer when it has one place to meet.\n\nStay with the crown for a few breaths. Then carry one thread of attention with you into whatever is next."
  },
  "taichong": {
    "why": "Tài Chōng — Great Surge — is a foot point traditionally associated with frustration and the idea of letting pent-up feeling move rather than stay clenched.",
    "script": "Let your feet rest on the floor if they can. Bring your attention to the top of one foot, near the space between the big toe and second toe.\n\nThis is Tài Chōng: Great Surge.\n\nNotice what irritation feels like in your body today. Maybe it is heat, a tight jaw, a restless leg, or simply the urge to be done with everything.\n\nNo need to judge it.\n\nBreathe in and let the feeling be present without making it bigger.\n\nBreathe out and imagine some of that pressure traveling down the legs toward the floor.\n\nAgain. In — notice what is still charged.\nOut — picture it moving downward.\n\nFrustration can carry useful information. You do not have to act on it in this moment to acknowledge that it is there.\n\nLet the floor take some of your weight. Let the jaw loosen. Let the hands stop rehearsing the argument.\n\nOne more breath with attention at the foot.\n\nThen notice whether there is even a little more room between the feeling and what you do next."
  },
  "zusanli": {
    "why": "Zú Sān Lǐ — Leg Three Miles — has a long traditional association with stamina; its name carries the image of finding enough steadiness for the next stretch of the road.",
    "script": "Bring your attention to your leg, about four finger-widths below the kneecap and just to the outside of the shinbone.\n\nThis is Zú Sān Lǐ: Leg Three Miles.\n\nIts old name carries a useful image — not endless energy, just enough for the next part of the road.\n\nNotice the difference between needing to finish everything and needing to begin one thing.\n\nBreathe in and imagine warmth gathering at the point on the leg.\n\nBreathe out and let that warmth travel upward, slowly, without urgency.\n\nAgain. In — a little warmth.\nOut — a little readiness.\n\nWhen motivation is low, the first movement can feel much larger than it is. You do not need momentum for the whole day. You need the first inch.\n\nChoose one small next thing in your mind. Nothing beyond it.\n\nTake one more breath with your attention at the leg.\n\nThree more miles can simply mean: enough for the next step."
  },
  "tanzhong": {
    "why": "At the center of the chest, Tán Zhōng — Sea of Tranquility — is traditionally associated with heaviness held around grief, loss, and emotional strain.",
    "script": "Rest one hand at the center of your chest, wherever it feels comfortable.\n\nThis is Tán Zhōng: Sea of Tranquility.\n\nNotice what is under your hand today — pressure, warmth, tightness, ache, or maybe nothing distinct at all.\n\nBreathe in without asking the feeling to change.\n\nBreathe out and let your hand stay there, warm and steady.\n\nGrief does not need to be solved in this practice. It does not need to become smaller, meaningful, or manageable on command.\n\nIn — let what is here be here.\nOut — let your hand keep it company.\n\nAgain. No performance. No requirement to feel better.\n\nThere can be relief in no longer holding a feeling at arm's length, even when the feeling itself remains.\n\nIf tears come, let them. If they do not, that is fine too.\n\nStay for as long as feels right. When you are ready, lower your hand slowly.\n\nNothing has to have changed for the time you spent here to count."
  },
  "laogong": {
    "why": "Láo Gōng — Palace of Labor — sits at the center of the palm and is traditionally associated with cooling agitation; here it becomes a simple sensory anchor for anxious energy.",
    "script": "Turn one palm face-up and bring your attention to its center.\n\nThis is Láo Gōng: Palace of Labor.\n\nRest your other hand lightly over the palm, or leave it open. Notice what is actually there — warmth, coolness, tingling, pressure, or very little at all.\n\nBreathe in and keep your attention with those sensations.\n\nBreathe out and imagine the hand becoming heavier, as if it could settle a little closer to the floor.\n\nAnxiety can pull attention upward and outward — toward what might happen, what needs fixing, what you may have missed.\n\nFor this breath, come back down to the palm.\n\nIn — notice the center of the hand.\nOut — let the fingers soften.\n\nAgain. Nothing to solve. Just contact, temperature, weight.\n\nIf your mind races away, return to one small physical detail in the palm.\n\nStay there for a few breaths, letting the hand be ordinary and present.\n\nWhen you are ready, bring your hands together or let them rest, and notice the room around you again."
  },
  "zhongwan": {
    "why": "Zhōng Wǎn — Middle Cavity — is an upper-abdominal point traditionally associated with digestion; this practice uses it as a place to notice and soften the way worry can feel in the stomach.",
    "script": "Rest one or both hands on your upper abdomen, midway between the breastbone and the navel.\n\nThis is Zhōng Wǎn: Middle Cavity.\n\nNotice what is under your hands without trying to interpret it — tightness, fluttering, fullness, warmth, or simply the movement of your breath.\n\nBreathe in and let the belly rise as much as is comfortable.\n\nBreathe out and see whether the muscles underneath your hands can soften by one degree.\n\nAgain. In — room for the breath.\nOut — a little less bracing.\n\nYou do not need to know exactly what you are worried about to notice how your body feels right now.\n\nLet your hands stay warm and steady while the breath moves beneath them.\n\nIf the mind starts looking for an explanation, return to sensation: hands, belly, breath.\n\nThere is nothing to untangle in this moment.\n\nStay for a few more rounds, allowing the abdomen to move naturally under your hands.\n\nWhen you are ready, let your hands fall away and notice what is present now, without grading the result."
  }
};

  POINTS.forEach((point) => {
    const copy = SESSION_COPY[point.id];
    if (!copy) return;
    point.why = copy.why;
    point.script = copy.script;
  });
})();
